options:
  juju-user:
    default: "user-admin"
    type: "string"
    description: "Juju API User"
  juju-secret:
    default:
    type: "string"
    description: "Juju Secret for API User"
  local-env:
    default: false
    type: boolean
    description: "Is this running in a local juju environment"
