options:
  juju-user:
    default: "user-admin"
    type: "string"
    description: "Juju API User"
  juju-secret:
    default:
    type: "string"
    description: "Juju Secret for API User"
  debug:
    default: false
    type: "boolean"
    description: "Enable debug/developer mode"
